Host heiress
  Hostname heiress.uio.no

Host waitress
  Hostname waitress.uio.no

Host zabbix-mgmt02
  User erikberg-drift
  Hostname zabbix-mgmt02.uio.no
  RequestTTY yes
  RemoteCommand tmux attach-session || tmux new-session

Host sm-linux9
  Hostname sm-linux9.uio.no
  User erikberg-drift

Host openshift-mgmt
  ProxyJump heiress
  User erikberg-drift
  Hostname openshift-mgmt.uio.no

Host ocp-provisioner
  ProxyJump openshift-mgmt
  User kni
  Hostname provisioner.ocp.uio.no
